name: cicd_test

on: [push]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo a string2
        run: echo "Hello hoge"
